import React from 'react'
import ax from '../../libs/ax'
import Head from 'next/head'

const DetailBlog = ({ data }) => {
	return (
		<div className="w-screen h-screen bg-slate-100 flex flex-col items-center">
			<Head>
				<title>Servial | {data.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<img src={data.banner.location} alt="" className="w-full h-[200px] object-cover" />
			<div className="w-full p-2">
				<h1 className="text-2xl font-bold"> {data.title}</h1>
				<p>{data.body}</p>
			</div>
		</div>
	)
}

export async function getServerSideProps(ctx) {
	const result = await ax.get(`/blog_read/${ctx.params.title}`)
	return {
		props: {
			title: ctx.params.title,
			data: await result.data.query,
		},
	}
}
export default DetailBlog
