import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import CardProduct from '../components/CardProduct'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import SearchBar from '../components/SearchBar'
import SwiperItems from '../components/SwiperItems'
import styles from '../styles/Home.module.css'
import { MdSecurity } from 'react-icons/md'
import axios from 'axios'
import Link from 'next/link'
export default function Home({ data }) {
	return (
		<div className="flex flex-col items-center bg-gray-100 w-screen h-auto min-h-screen">
			<Head>
				<title>Servial</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main className="w-screen min-h-screen  p-5">
				<div className="searchBar w-full h-12 mt-14">
					<SearchBar />
				</div>

				<div className="w-full h-14 mt-6 ">
					<SwiperItems />
				</div>

				<div className="cardProduct w-full flex flex-wrap gap-4 overflow-y-scroll justify-between pb-14 ">
					{data.map((e) => {
						return (
							<CardProduct
								key={e.id}
								title={e.title}
								berat={e?.berat}
								satuanBerat={e?.satuan_berat}
								imgProduct={e.photo[0].location}
							/>
						)
					})}
				</div>
			</main>

			<Footer />
		</div>
	)
}

export async function getServerSideProps() {
	const result = await axios.get('http://localhost:9000/api/product_read')
	return {
		props: {
			data: result.data.query,
		},
	}
}
